config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'get_user' => 'users#get_user'
  get 'render_post' => 'posts#render_post'
  get 'active_chatrooms' => 'chatrooms#active_chatrooms'
  resources :users do
    resources :posts do
      resources :comments, :only => [:show, :create, :destroy, :edit, :update, :new] do
        member do
          post 'like'
        end
      end
      member do
        get 'show_comments'
        post 'like'
      end
    end
    resources :friendships, only: [:index, :destroy, :update, :create]
  end

  resources :chatrooms do
    resources :messages
    member do
      get 'del_from_sessions'
      get 'open_chat'
    end
  end

  devise_scope :user do
    authenticated :user do
      #root 'users#index', as: :authenticated_root
      root 'home#index', as: :authenticated_root
      get 'home/autocomplete_user_username'
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :likes, as: :likeable
  has_ancestry
  validates :content, length: { maximum: 255, minimum: 4}
  has_attached_file :image, styles: { medium: "250>", thumb: "100x100>", lightbox: "1200>" }, default_url: ":style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validate :max_depth, on: :create

  # limits depth of comments.
  def max_depth
    if depth > 1
      errors.add(:parent_id, 'you can reply only on root comments')
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new(parent_id: params[:parent_id])
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    @comment.save
    respond_to do |format|
      format.html {
        flash[:notice] = 'Comment added.'
        redirect_to :back
      }
      format.js
    end

  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to authenticated_root_path
  end

  def edit
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    respond_to do |f|
      f.js
    end
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update comment_params
    respond_to do |f|
      f.html {
        redirect_to authenticated_root_path
      }
      f.js
    end
  end

  def like
    @comment = Comment.find(params[:id])
    @user = current_user
    if @like = Like.find_by(likeable: @comment, user: @user)
      @like.destroy
      respond_to do |format|
        format.js
      end
    else
      Like.create(likeable: @comment, user: @user, like: true)
      respond_to do |format|
        format.js
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :image, :parent_id)
  end

  def find_user
    @user = current_user
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def children_count(comment)
    comment.children.count
  end
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
    <div id="comment" class="comment_<%=comment.id%> clearfix">
      <%= link_to image_tag(comment.user.avatar(:thumb)), comment.user, class: 'comment_avatar' %>
      <div id="comment_content"><%= render 'comments/content', comment: comment %></div>
    </div>
<% end %>

app/views/comments/_content.html.erb
<div class="com_content_<%=comment.id%>">
  <%= link_to " #{comment.user.username }", comment.user, class: 'commenter' %>
  <span class="com_content"><%= comment.content %></span><br>
  <div>
    <% if comment.image.file? %>
        <%= link_to comment.image.url(:lightbox), class: 'post_thumb' do %>
            <%= image_tag comment.image.url(:medium), id: "com_img com_img_#{comment.id}" %>
        <% end %>
    <% end %>
  </div>
      <div class="authorized_links">
        <% if current_user == comment.user %>
        <span>
          <%= link_to edit_user_post_comment_path(comment.user, comment.post, comment), class: "edit", remote: true do %>
            <i class="fa fa-pencil" aria-hidden="true"></i>
          <% end %>
        </span>
        <span>
          <%= link_to user_post_comment_path(comment.user, comment.post, comment), method: :delete, class: "delete" do %>
            <i class="fa fa-trash" aria-hidden="true"></i>
          <% end %>
        </span>
        <% end %>
        <% if comment.root? %>
          <%= link_to "replies (#{children_count(comment)})", '#', class: 'toggle_replies', data: {id: comment.id} %>
        <% end %>
        <small id="time"><%= time_ago_in_words(comment.created_at) %> ago.</small>
        <div class="likes">
          <% if !current_user.likes?(comment) %>
            <span class="like_<%= comment.id %>">
              <%= render 'comments/like', comment: comment %>
            </span>
          <% else %>
            <span class="unlike_<%= comment.id %>">
              <%= render 'comments/unlike', comment: comment %>
            </span>
          <% end %>
          <span class="comment_likers_<%=comment.id%>">
            <%= comment.likes.size %>
          </span>
        </div>
      </div>

  <div class="replies replies_<%=comment.id%>">
    <% if comment.has_children? %>
      <% comment.children.each do |com| %>
        <div class="reply"><%= render com, post: comment.post %></div>
      <% end %>
    <% end %>
    <% if comment.root? %>
      <%= render 'comments/new_reply', post: comment.post, comment: comment %>
    <% end %>
  </div>
</div>

app/views/comments/_edit.html.erb
<div class="add_comment edit_<%=@comment.id%> edit_comment">
  <%= form_for [@user, @post, @comment], remote: true do |f| %>

      <div class="field">
        <%= f.text_area :content, class: 'comment_area'  %>
      </div>

      <div class="field avatar_button">
        <%= f.label :image, class: 'fileContainer' do %>
            <i class="fa fa-camera tooltip" aria-hidden="true"></i>
            <%= f.file_field :image, class: "img_com_upl edit_#{post.id}" %>
        <% end %>
      </div>
      <%= f.submit 'Edit', class: 'add_comment' %>
      <% if @comment.image.file? %>
        <%= image_tag @comment.image.url(:thumb), class: "edit_img_preview edit_#{post.id}" %>
      <% else %>
        <div class="comment_img_preview"><img class="edit_img_preview edit_<%=post.id%>"/></div>
      <% end %>
  <% end %>
</div>

app/views/comments/_like.html.erb
<span class="like">
  <span class="comment_like_<%= comment.id %>">
    <%= link_to like_user_post_comment_path(current_user, comment.post , comment), method: 'post', remote: true do %>
      <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
    <% end %>
  </span>
</span>

app/views/comments/_new.html.erb
<div class="add_comment clearfix">
  <%= form_for [current_user, post, Comment.new], html: { multipart: true }, remote: true do |f| %>
      <%= f.hidden_field :parent_id %>
      <%= link_to image_tag(current_user.avatar(:thumb)), current_user, class: 'comment_avatar' %>
      <div class="field">
        <%= f.text_area :content, class: 'comment_area' %>
      </div>
      <div class="field avatar_button">
        <%= f.label :image, class: 'fileContainer' do %>
            <i class="fa fa-camera tooltip" aria-hidden="true"></i>
            <%= f.file_field :image, class: "img_com_upl img_#{post.id}" %>
        <% end %>
      </div>
      <%= f.button :submit, class: 'add_comment' do %>
        <i class="fa fa-share-square-o" aria-hidden="true"></i>
      <% end %>
  <% end %>
  <div class="comment_img_preview"><img class="img_<%=post.id%>"/></div>
</div>

app/views/comments/_new_reply.html.erb
<div class="add_reply clearfix">
  <%= form_for [current_user, post, Comment.new(parent_id: comment.id)], html: { multipart: true }, remote: true do |f| %>
      <%= f.hidden_field :parent_id %>
      <%= link_to image_tag(current_user.avatar(:thumb)), current_user, class: 'comment_avatar' %>
      <div class="field">
        <%= f.text_area :content, class: 'comment_area' %>
      </div>
      <div class="field avatar_button">
        <%= f.label :image, class: 'fileContainer' do %>
            <i class="fa fa-camera tooltip" aria-hidden="true"></i>
            <%= f.file_field :image, class: "img_com_upl img_#{post.id}" %>
        <% end %>
      </div>
      <%= f.button :submit, class: 'submit_reply' do %>
          <i class="fa fa-share-square-o" aria-hidden="true"></i>
      <% end %>
  <% end %>
  <div class="comment_img_preview"><img class="img_<%=post.id%>"/></div>
</div>

app/views/comments/_reply.html.erb
<%= div_for comment do %>
    <div id="comment" class="clearfix">
      <%= link_to image_tag(comment.user.avatar(:thumb)), comment.user, class: 'comment_avatar' %>
      <div id="comment_content">
        <div class="com_content_<%=comment.id%>">
          <%= link_to " #{comment.user.username }", comment.user, class: 'commenter' %>
          <span class="com_content"><%= comment.content %></span><br>
          <div>
            <% if comment.image.file? %>
                <%= link_to comment.image.url(:lightbox), class: 'post_thumb' do %>
                    <%= image_tag comment.image.url(:medium), id: "com_img com_img_#{comment.id}" %>
                <% end %>
            <% end %>
          </div>
          <div class="authorized_links">
            <% if current_user == comment.user %>
          <span>
            <%= link_to edit_user_post_comment_path(comment.user, comment.post, comment), class: "edit", remote: true do %>
              <i class="fa fa-pencil" aria-hidden="true"></i>
            <% end %>
          </span>
          <span>
            <%= link_to user_post_comment_path(comment.user, comment.post, comment), method: :delete, class: "delete" do %>
              <i class="fa fa-trash" aria-hidden="true"></i>
            <% end %>
          </span>
            <% else %>
            <span>
              <%= link_to 'reply', new_user_post_comment_path(current_user, comment.post, parent_id: comment), class: "reply_link #{comment.id}" %>
            </span>
            <% end %>
            <small id="time"><%= time_ago_in_words(comment.created_at) %> ago.</small>
            <div class="likes">
              <% if !current_user.likes?(comment) %>
              <span class="like_<%= comment.id %>">
                <%= render 'comments/like', comment: comment %>
              </span>
              <% else %>
              <span class="unlike_<%= comment.id %>">
                <%= render 'comments/unlike', comment: comment %>
              </span>
              <% end %>
              <span class="comment_likers_<%=comment.id%>">
              <%= comment.likes.size %>
            </span>
            </div>
          </div>

          <div class="replies replies_<%=comment.id%>">
            <% if comment.has_children? %>
                <% comment.children.each do |com| %>
                    <%= render com, post: comment.post %>
                <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/comments/_unlike.html.erb
<span class="unlike">
  <span class="comment_unlike_<%= comment.id %>">
    <%= link_to like_user_post_comment_path(current_user, comment.post, comment), method: 'post', remote: true do %>
      <i class="fa fa-thumbs-o-down" aria-hidden="true"></i>
    <% end %>
  </span>
</span>

app/views/comments/create.js.erb
<% if @comment.errors.empty? %>
    $("ul#comment_error").html('');
    <% if @comment.root? %>
      $('.comments_<%= @comment.post.id %>').append("<%= escape_javascript(render @comment) %>");
      $('.replies_<%=@comment.id%>').hide();
    <% else %>
      $('.com_content_<%=@comment.parent.id %> .replies').prepend("<%= escape_javascript(render @comment) %>");
    <% end %>
  <% else %>
    $("ul#comment_error").html(''); // clear earlier flash messages if any.
    <% if @comment.errors.any? %>
      <% @comment.errors.full_messages.each do |msg|  %>
        $("ul#comment_error").append($("<li />").html("<%= msg.html_safe %>"));
      <% end %>
    <% end %>
    $("ul#comment_error").css('opacity', '1');
    $("#comment_error").delay(3200).animate({'opacity': '0'}, 400);
<% end %>

$('.comment_area').val('');
$('.comment_area').css('height', '25px');
$('.comment_img_preview img').attr('src', '');

app/views/comments/edit.js.erb
$('.com_content_<%=@comment.id%>').html('<%= escape_javascript(render 'comments/edit', user: @user, post: @comment.post, comment: @comment)%>');

app/views/comments/like.js.erb
<% if Like.find_by(likeable: @comment, user: @user) %>
  $(".comment_like_<%= @comment.id %>").html("<%= escape_javascript(render 'comments/unlike', user: @user, comment: @comment) %>");
<% else %>
  $(".comment_unlike_<%= @comment.id %>").html("<%= escape_javascript(render 'comments/like', user: @user, comment: @comment) %>");
<% end %>

$('.comment_likers_<%=@comment.id%>').html("<%= @comment.likes.count %>");

app/views/comments/new.html.erb
<div class="add_comment clearfix">
  <%= form_for [current_user, @post, @comment], html: { multipart: true }, remote: true do |f| %>
      <%= f.hidden_field :parent_id %>
      <%= link_to image_tag(current_user.avatar(:thumb)), current_user, class: 'comment_avatar' %>
      <div class="field">
        <%= f.text_area :content, class: 'comment_area' %>
      </div>
      <div class="field avatar_button">
        <%= f.label :image, class: 'fileContainer' do %>
            <i class="fa fa-camera tooltip" aria-hidden="true"></i>
            <%= f.file_field :image, class: "img_com_upl img_#{@post.id}" %>
        <% end %>
      </div>
      <%= f.button :submit, class: 'add_comment' do %>
          <i class="fa fa-share-square-o" aria-hidden="true"></i>
      <% end %>
  <% end %>
  <div class="comment_img_preview"><img class="img_<%=@post.id%>"/></div>
</div>

app/views/comments/update.js.erb
$('.comment_<%=@comment.id%>').replaceWith('<%= escape_javascript(render 'comments/comment', comment: @comment) %>');
<% if @comment.root? %>
 $('.replies_<%=@comment.id%>').hide();
<% end %>