config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'get_user' => 'users#get_user'
  get 'render_post' => 'posts#render_post'
  get 'active_chatrooms' => 'chatrooms#active_chatrooms'
  resources :users do
    resources :posts do
      resources :comments, :only => [:show, :create, :destroy, :edit, :update, :new] do
        member do
          post 'like'
        end
      end
      member do
        get 'show_comments'
        post 'like'
      end
    end
    resources :friendships, only: [:index, :destroy, :update, :create]
  end

  resources :chatrooms do
    resources :messages
    member do
      get 'del_from_sessions'
      get 'open_chat'
    end
  end

  devise_scope :user do
    authenticated :user do
      #root 'users#index', as: :authenticated_root
      root 'home#index', as: :authenticated_root
      get 'home/autocomplete_user_username'
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
  has_many :likes
  scope :username_like, -> (name) { where("username ilike ?", name)}
  has_many :messages
  has_many :chatrooms, through: :chatroom_users
  has_many :chatroom_users, :dependent => :destroy

  has_many :friendships
  has_many :accepted_friendships, -> { where(status: Friendship.statuses[:accepted]) }, class_name: 'Friendship'
  has_many :requested_friendships, -> { where(status: Friendship.statuses[:requested]) }, class_name: 'Friendship'
  has_many :pending_friendships, -> { where(status: Friendship.statuses[:pending]) }, class_name: 'Friendship'

  #accetped friends
  has_many :friends, through: :accepted_friendships, after_remove: :remove_complement_friendship

  #users that requested friendship with user
  has_many :requested_friends, through: :requested_friendships, source: :friend

  #users that user requested friendship with
  has_many :pending_friends, through: :pending_friendships, source: :friend

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login
  validates :username, :presence => true, :uniqueness => { :case_sensitive => false }
  has_attached_file :avatar, styles: { medium: "40x40!", thumb: "30x30!", big: "250x250>" }, default_url: ":style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_hash).first
    end
  end

  # Returns true when the user likes post.
  def likes?(likeable)
    Like.find_by(likeable: likeable, user: self, like: true)
  end

  def get_friendship(user)
    Friendship.where(user_id: self, friend_id: user).first
  end

  def is_friends_with?(user)
    Friendship.exists?(user_id: self, friend_id: user, status: Friendship.statuses[:accepted])
  end

  def request_pending?(user)
    Friendship.exists?(user_id: self, friend_id: user, status: Friendship.statuses[:requested])
  end

  def requested_friendship?(user)
    Friendship.exists?(user_id: self, friend_id: user, status: Friendship.statuses[:pending])
  end

  def unaccepted_friends
    requested_friends + pending_friends
  end

  def feed
    friends_ids = friends.ids
    Post.where("user_id IN (:friends_ids) OR user_id = :user_id", friends_ids: friends_ids, user_id: id)
  end

  def get_chatroom_with(friend)
    #Chatroom.joins(:users).where("users.id" => [self.id, friend.id]).where("users.id" => [friend.id]).last
    self.chatrooms.includes(:users).each do |chatroom|
      if chatroom.users.first == friend || chatroom.users.second == friend
        Rails.logger.info "************************** #{chatroom.users.first.username} ****************************"
        return chatroom
      end
    end
  end

  private

  def create_complement_friendship(friend)
    self.friends << friend unless friend.friends.include?(self)
  end

  def remove_complement_friendship(friend)
    friend.friends.delete(self)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if params[:friends]
      @users = User.includes(:requested_friendships).find(params[:friends]).unaccepted_friends
    else
      @users = User.all.includes(:requested_friendships)
    end

    if params[:search]
      @users = User.username_like("%#{params[:search]}%")
    end
  end

  def show
    @user = User.where(id: params[:id]).last
    @posts = @user.posts
  end

  def get_user
    render json: {name: current_user.username}
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friends_links.html.erb
<div class="friends_links">
  <% if current_user.requested_friendship?(user) %>
      <span class="sent">Friendship request sent.</span>
  <% elsif current_user.request_pending?(user) %>
      <%= link_to user_friendship_path(user.id, current_user.get_friendship(user)), method: :put, class: "accept", remote: true  do %>
          Accept request <i class="fa fa-user-plus" aria-hidden="true"></i>
      <% end %>
      <%= link_to user_friendship_path(current_user, current_user.get_friendship(user)), method: :delete, class: "refuse", remote: true do %>
          Refuse request <i class="fa fa-user-times" aria-hidden="true"></i>
      <% end %>
  <% elsif !current_user.is_friends_with?(user) && current_user != user%>
      <%= link_to user_friendships_path(user.id), method: :post, class: "send", remote: true do %>
          Send request <i class="fa fa-plus" aria-hidden="true"></i>
      <% end %>
  <% elsif current_user.is_friends_with?(user) %>
      <%= link_to user_friendship_path(current_user, current_user.get_friendship(user)), method: :delete, class: "delete", remote: true do %>
          Delete friend <i class="fa fa-minus" aria-hidden="true"></i>
      <% end %>
  <% end %>
</div>

app/views/users/_user.html.erb
<div class="user_ind">
  <%= link_to user do %>
      <%= image_tag user.avatar.url(:medium), class: 'small_avatar' %><span class='username'><%= user.username %></span>
  <% end %>
  <span class="friendship_links friend_<%=user.id%>"><%= render 'users/friends_links', user: user %></span>
</div>

app/views/users/index.html.erb
<div class="users_index">
  <ul class="users">
    <% if @users.any? %>
      <% @users.each do |user| %>
          <li><%= render user%></li>
      <% end %>
    <% else %>
        No users found.
    <% end %>
  </ul>
</div>

app/views/users/show.html.erb
<div class="user posts">
  <div class="core">
    <%= @user.username %>
    <%= image_tag @user.avatar.url(:big) %>
  </div>
  <div class="friendship_links friend_<%=@user.id%>"><%= render 'users/friends_links', user: @user %></div>
  <%= render partial: 'posts/post', collection: @posts %>
</div>