config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'get_user' => 'users#get_user'
  get 'render_post' => 'posts#render_post'
  get 'active_chatrooms' => 'chatrooms#active_chatrooms'
  resources :users do
    resources :posts do
      resources :comments, :only => [:show, :create, :destroy, :edit, :update, :new] do
        member do
          post 'like'
        end
      end
      member do
        get 'show_comments'
        post 'like'
      end
    end
    resources :friendships, only: [:index, :destroy, :update, :create]
  end

  resources :chatrooms do
    resources :messages
    member do
      get 'del_from_sessions'
      get 'open_chat'
    end
  end

  devise_scope :user do
    authenticated :user do
      #root 'users#index', as: :authenticated_root
      root 'home#index', as: :authenticated_root
      get 'home/autocomplete_user_username'
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable
  validates :content, length: { maximum: 1000, minimum: 10}
  has_attached_file :image, styles: { medium: "550x450>", thumb: "100x100>", lightbox: "1200>" }, default_url: ":style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :find_user, only: [:create, :index]
before_action :find_user_and_post, only: [:show, :edit, :destroy, :update]

  def index
    @posts = @user.posts.includes(:comments).order('created_at DESC')
  end

  def create
    @post = @user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.json { render json: @post }
      else
        format.json { render json: { error: @post.errors.full_messages }, status: 422 }
      end
    end
  end

  def show
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    @post.update post_params
    respond_to do |f|
      f.js
    end
  end

  def destroy
    @post.destroy
    redirect_to authenticated_root_path
    flash[:notice] = 'Post deleted.'
  end


  def show_comments
    @user = User.where(id: params[:user_id]).last
    @post = Post.where(id: params[:id]).last
    respond_to do |format|
      if @post.comments.count < 20
        format.js
      else
        format.html {
          redirect_to @post
        }
      end
    end
  end

  def like
    @post = Post.find(params[:id])
    @user = current_user
    if @like = Like.where(likeable: @post, user: @user).first
      @like.destroy
      respond_to do |format|
        format.html {
          flash[:success] = "Like Updated!"
          redirect_to :back
        }
        format.js
      end
    else
      Like.create(likeable: @post, user: @user, like: true)
      respond_to do |format|
        format.html {
          flash[:success] = "Like Updated!"
          redirect_to :back
        }
        format.js
      end
    end
  end

  def render_post
    @post = Post.find(params[:id])
    render json: {view: render_to_string(partial: '/posts/post', :locals => {:post => @post })}
  end


private

  def post_params
    params.require(:post).permit(:content, :image)
  end

  def find_user
    @user = User.where(id: params[:user_id]).last
  end

  def find_user_and_post
    @user = User.where(id: params[:user_id]).last
    @post = @user.posts.where(id: params[:id]).last
  end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_edit.html.erb
<div class="edit_partial clearfix">
  <%= form_for [@user, @post], html: { multipart: true }, remote: true do |f| %>

      <div class="field">
        <%= f.text_area :content, class: 'content_area' %>
      </div>

      <div>
        <% if @post.image.file? %>
            <%= link_to @post.image.url(:lightbox), class: 'post_thumb' do %>
                <%= image_tag @post.image.url(:medium), class: "edit_post_prev post_image_#{@post.id}" %>
            <% end %>
        <% else %>
          <div class="post_img_preview"><img class="edit_post_prev edit_<%=post.id%>"/></div>
        <% end %>
      </div>

      <div class="field avatar_button">
        <%= f.label :image, class: 'fileContainer' do %>
            <span class="tooltip">Change Image</span>
            <%= f.file_field :image, class: 'edit_post_image' %>
        <% end %>
      </div>

      <%= f.submit 'Edit', id: 'edit_post' %>
  <% end %>
</div>

app/views/posts/_like.html.erb
<span class="like">
  <span class="post_like_<%= post.id %>">
    <%= link_to like_user_post_path(current_user, post), method: 'post', remote: true do %>
      Like <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
    <% end %>
  </span>
</span>

app/views/posts/_post.html.erb
<div class="post post_<%= post.id%>">
  <div class="top">
    <%= image_tag post.user.avatar.url(:medium), class: 'avatar' %>
    <div class="text">
    <%= link_to post.user.username, post.user, class: 'nick' %>
    <br><small><%= link_to post.created_at.strftime('%d %b %Y %H:%M'), user_post_path(post.user, post), class: 'timestamp' %></small>
    </div>
  </div>
  <div class="post_con_<%=post.id%>">
    <div class="post_content"><%= post.content %></div>
    <div>
      <% if post.image.file? %>
        <%= link_to post.image.url(:lightbox), class: 'post_thumb' do %>
          <%= image_tag post.image.url(:medium), id: "image_#{post.id}" %>
        <% end %>
        <div class='box'></div>
      <% end %>
    </div>
  </div>
  <div class="links">
    <% if current_user == post.user %>
      <small><%= link_to 'Delete', user_post_path(post.user, post), method: :delete %></small>
      <small><%= link_to 'Edit', edit_user_post_path(post.user, post), class: "edit_link", data: {post: post.id}, remote: true %></small>
    <% end %>
    <% if post.comments.count > 3 %>
      <small><%= link_to "More comments(#{post.comments.count})", show_comments_user_post_path(post.user, post), class: "more_comments more_#{post.id}", remote: true %></small>
    <% end %>
    <div class="likes">
      <% if !current_user.likes?(post) %>
        <span class="like_<%= post.id %>">
          <%= render 'posts/like', post: post %>
        </span>
      <% else %>
        <span class="unlike_<%= post.id %>">
          <%= render 'posts/unlike', post: post %>
        </span>
      <% end %>
      <span class="likers" id="likers_<%= post.id %>">
        (<%= pluralize( post.likes.size, "like") %>)
      </span>
    </div>
  </div>
  <div class="comments">
    <div class="comments_<%= post.id %>">
      <%= render post.comments.roots.order(' likes_count DESC, created_at DESC').includes(:user).limit(3) %>
    </div>
    <%= render 'comments/new', post: post %>
  </div>
</div>

app/views/posts/_unlike.html.erb
<span class="unlike">
  <span class="post_unlike_<%= post.id %>">
    <%= link_to like_user_post_path(current_user, post, like: false), method: 'post', remote: true do %>
      Unlike <i class="fa fa-thumbs-o-down" aria-hidden="true"></i>
    <% end %>
  </span>
</span>

app/views/posts/edit.js.erb
$('.post_con_<%= @post.id %>').html("<%= escape_javascript(render partial: 'posts/edit', user: @user, post: @post) %>");

/*$(document).delegate('.edit_link', 'click', function (e) {
 e.preventDefault();
 var post_id = $(this).data("post");
 $(this).html(post_id);
 $('post_con_'+post_id).html()
 });*/

app/views/posts/index.html.erb
<div class="users_posts">
  <div class="posts">
    <%= render partial: 'posts/post', collection: @posts %>
  </div>
</div>

app/views/posts/like.js.erb
<% if Like.find_by(likeable: @post, user: @user) %>
  $(".post_like_<%= @post.id %>").html("<%= escape_javascript(render 'posts/unlike', user: @user, post: @post) %>");
<% else %>
  $(".post_unlike_<%= @post.id %>").html("<%= escape_javascript(render 'posts/like', user: @user, post: @post) %>");
<% end %>

$("#likers_<%= @post.id %>").html(" (<%= pluralize( @post.likes.count, "like") %>) ");

app/views/posts/show.html.erb
<%= render @post %>

app/views/posts/show_comments.js.erb
$('.comments_<%= @post.id %>').html("<%= escape_javascript(render @post.comments) %>");
$('.replies').hide();
$('.more_<%= @post.id%>').remove();

app/views/posts/update.js.erb
<% if @post.errors.empty? %>
  $("ul#comment_error").html('');
  $('.post_<%=@post.id%>').replaceWith('<%= escape_javascript(render 'posts/post', post: @post) %>');
  $('.replies').hide();
<% else %>
  $("ul#comment_error").html(''); // clear earlier flash messages if any.
  <% @post.errors.full_messages.each do |msg|  %>
    $("ul#comment_error").append($("<li />").html("<%= msg.html_safe %>"));
  <% end %>
$("ul#comment_error").css('opacity', '1');
  $("#comment_error").delay(3200).animate({'opacity': '0'}, 400);
<% end %>