config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'get_user' => 'users#get_user'
  get 'render_post' => 'posts#render_post'
  get 'active_chatrooms' => 'chatrooms#active_chatrooms'
  resources :users do
    resources :posts do
      resources :comments, :only => [:show, :create, :destroy, :edit, :update, :new] do
        member do
          post 'like'
        end
      end
      member do
        get 'show_comments'
        post 'like'
      end
    end
    resources :friendships, only: [:index, :destroy, :update, :create]
  end

  resources :chatrooms do
    resources :messages
    member do
      get 'del_from_sessions'
      get 'open_chat'
    end
  end

  devise_scope :user do
    authenticated :user do
      #root 'users#index', as: :authenticated_root
      root 'home#index', as: :authenticated_root
      get 'home/autocomplete_user_username'
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/views/layouts/_friend_list.html.erb
<div class="friend_list">
  <ul>
    <% users.each do |user| %>
        <% unless Chatroom.exist?(current_user, user) %>
            <%= link_to chatrooms_path(friend: user.username), method: :post, remote: true, data: {behavior: 'chatroom-link', user: user.id} do %>
                <li>
                  <%= image_tag user.avatar.url(:thumb) %>
                  <span><%= user.username %></span>
                </li>
            <% end %>
        <% else %>
            <%= link_to open_chat_chatroom_path(current_user.get_chatroom_with(user)), remote: true, data: {behavior: 'chatroom-link', chatroom_id: current_user.get_chatroom_with(user).id} do %>
                <li>
                  <%= image_tag user.avatar.url(:thumb) %>
                  <span><%= user.username %></span>
                </li>
            <% end %>
        <% end %>
    <% end %>
  </ul>
</div>

app/views/layouts/_nav.html.erb
<!-- NAV -->
<div class="nav" style="clear:both">
  <ul>
    <li class="Logo"><%= link_to 'MyChat',  "/"%></li>
    <% if user_signed_in? %>
      <li class="Option">
        <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out" aria-hidden="true"></i> <span class="nav_text">Sign out</span>
        <% end %>
      </li>
      <li class="Option">
        <%= link_to edit_user_registration_path do %>
          <i class="fa fa-cog" aria-hidden="true"></i> <span class="nav_text">Settings</span>
        <% end %>
      </li>
      <% if current_user.requested_friends.any? %>
        <li class="news">
          <%= link_to users_path(friends: current_user.id) do %>
              <i class="fa fa-comment-o" aria-hidden="true"></i> <span class="nav_text pending"><%=current_user.requested_friends.count%></span>
          <% end %>
        </li>
      <% end %>
      <li class="Option">
        <%= link_to current_user do %>
            <%= image_tag current_user.avatar.url(:thumb), id: 'nav_avatar' %> <span class="nav_text">My Profile</span>
        <% end %>
      </li>
      <li class="Option">
        <%= link_to authenticated_root_path do %>
            <i class="fa fa-home" aria-hidden="true"></i> <span class="nav_text">Home</span>
          <% end %>
      </li>
      <li class="Option">
        <%= link_to users_path do %>
          <i class="fa fa-users" aria-hidden="true"></i> <span class="nav_text">Users</span>
        <% end %>
      </li>
      <li class="Option">
        <div class="search">
          <%= form_tag users_path, method: 'get', id: 'search-form' do %>
              <%= autocomplete_field_tag :search, 'Find your friends...', home_autocomplete_user_username_path,
                'min-length' => 1, class:'search_field', onfocus: 'if($(this).val()=="Find your friends..."){$(this).val("");};',
                 onblur: 'if($(this).val()==""){$(this).val("Find your friends...");};', 'data-noMatchesLabel' => 'no users found' %>
          <% end %>
          <script type="text/javascript" charset="utf-8">
            $('#search').bind('railsAutocomplete.select', function(event, data){
              $('#search-form').submit();
              window.location.href = '/users/' + data.item.id;
            });
          </script>
        </div>
      </li>
    <% else %>
      <li class="Option"><%= link_to 'Sign in', new_user_session_path %></li>
      <li class="Option"><%= link_to 'Sign up', new_user_registration_path %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chat</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta content='<%= user_signed_in? ? current_user.id : "" %>' name='user-id'/>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="backdrop"></div>
<%= render 'layouts/nav' %>
  <div class="container">

  <div class="flashes">
    <% flash.each do |key, value| %>
        <%= content_tag :div, value, class: "flash #{key}" %>
    <% end %>
    <ul id="notice"></ul>
    <ul id="comment_error"></ul>
  </div>
  <% if current_user %>
    <%= render 'layouts/friend_list', users: (User.all - [current_user]) %>
  <% end %>
  <%= yield %>
</div>
<div class="footer"></div>
</body>
</html>